server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
        

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB 
      max-request-size: 20MB        
  datasource:
#    url: jdbc:log4jdbc:mysql://192.168.0.85:3306/arts_center?serverTimezone=Asia/Seoul
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://localhost:3306/arts_center?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  mail:
    host: smtp.naver.com
    port: 465
    username: jdy1787@naver.com
    password: 3609acac!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
      
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  
#  sql: 
#    init:
#      schema-locations:
#      - classpath:db/table.sql  
#      data-locations:
#      - classpath:db/data.sql
#      
#  h2:
#    console:
#      enabled: true
#  output:
#    ansi: 
#      enabled: always
  
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    
    
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: INFO
#    javax:
#      sql:
#        DataSource: OFF
#    jdbc:
#      audit: OFF
#      resultset: OFF
#      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
#      sqlonly: OFF     #SQL만 로그로 남긴다.
#      sqltiming: INFO    #SQL과 소요시간을 표기한다.
#      connection : OFF  # 커넥션 확인가능
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
      
