server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
        

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB 
      max-request-size: 20MB
          
  datasource:
    url: jdbc:mysql://localhost:3306/arts_center?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: b
    password: asd1234!

  
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    